version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0-stretch-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: newsroom
          RAILS_ENV: test
          DATABASE_URL: postgres://127.0.0.1:5432/newsroom_test
      - image: circleci/postgres:11.1-alpine
        environment:
          POSTGRES_USER: newsroom
          POSTGRES_DB: newsroom_test
          POSTGRES_PASSWORD: ""
      - image: redis
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace
      - run:
          name: Run rspec
          command: bundle exec rake
      - store_test_results:
          path: test_results
